name: PearRewards
version: 1.0
api-version: 1.15
description: Plugin per i daily rewards
author: PereCraft
main: pearrewards.PearRewards
commands:
    pearrewards:
        description: Gestione del plugin
        aliases: [pr]
    daily:
        description: Mostra la gui per riscattare i reward
        